version: '3'
services:
  frontend:
    build:
      context: ../BarcelonaFrontEnd
      dockerfile: src/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../BarcelonaBackEnd
      dockerfile: BarcelonaBackEnd/Dockerfile
    ports:
      - "8080:8080"  # Make internal and external port the same for consistency
      - "7189:443"  # HTTPS port
    environment:
      - ASPNETCORE_LOGGING__CONSOLE__LOGLEVEL__MICROSOFT_ASPNETCORE_SIGNALR=Debug
