version: '3'
services:
  frontend:
    build:
      context: ../BarcelonaFrontEnd  # Path to the frontend project relative to BarcelonaCompose
      dockerfile: src/Dockerfile      # Path to Dockerfile inside the frontend repo
    ports:
      - "4200:80"  # Angular app will be available at http://localhost:4200
    depends_on:
      - backend

  backend:
    build:
      context: ../BarcelonaBackEnd    # Path to the backend project relative to BarcelonaCompose
      dockerfile: BarcelonaBackEnd/Dockerfile      # Path to Dockerfile inside the backend repo
    ports:
      - "5209:80"  # Exposing backend on http://localhost:5209
      - "7189:443" # Exposing backend on https://localhost:7189 (for HTTPS)
