version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"  # Frontend Angular app port mapping
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:80"  # Backend .NET app port mapping
